### ISSUE TITLE
neoprene future

### ISSUE THREAD

**Issue by skbolton** [rorymadden/neoprene#11]
What made you stop working on Neoprene?

**Comment by rorymadden** [comment]
Hi Stephen - two things: 

1. I never got it working properly. I was trying to build a product and I spent all of my time on trying to simplify the ORM layer. I gave up on it and just used the API directly in order to speed up on the product. 

2. The product failed (see point 1 above). Since then I haven't had a use case to use Neo4j so I haven't kept it up to date. 

If you want to take on the proejct I'd be happy to make you a maintainer / hand over the project. 

Cheers,
Rory
